<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Les styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/icons.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('library/font-awesome-4.7.0/css/font-awesome.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/script.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))

        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top col-12" role="navigation">
            <div class="container">
                <div class="navbar-header d-flex">
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <i class="fa fa-2x fa-linode" aria-hidden="true"></i>
                    </a>
                    <div class="navbar-brand">Location Logement</div>
                    <div class="navbar-brand navigation-trigger m-auto">
                        <div class="navigation-btn">
                            <i class="navigation-btn-line"></i>
                            <i class="navigation-btn-line"></i>
                            <i class="navigation-btn-line"></i>
                        </div>
                    </div>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?= $this->url('home') ?>">Home</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="lateral-menu sidebar">
            <div class="row">
                <div class="col-12 user p-0">
                    <div class="user__info" data-toggle="dropdown">
                        <img class="user__img" src="https://img11.hostingpics.net/pics/177979photo.jpg" alt="">
                        <div>
                            <div class="user__name">Jonathan Rodrigues</div>
                            <div class="user__email">j.rodrigues@alphalives.com</div>
                        </div>
                    </div>
                    <ul class="navigation p-0">
                        <li><a href="/application"> <i class="fa fa-home" aria-hidden="true"></i> Accueil</a></li>
                        <li><a href="/moncompte"> <i class="fa fa-user" aria-hidden="true"></i> Mon compte</a></li>
                        <li><a href="/annonces-marques"> <i class="fa fa-bookmark" aria-hidden="true"></i>Mes annonces marqués</a></li>
                        <li><a href="/login"> <i class="fa fa-power-off" aria-hidden="true"></i>Déconnexion</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container-fluid p-0">
            <?= $this->content ?>
        </div>
        <footer class="container-fluid">
            <div class="row">
                <div class="container">
                    <p>&copy; <?= date('Y') ?> by Rodrigues/Curiel. All rights reserved.</p>
                </div>
            </div>
        </footer>
        <?= $this->inlineScript() ?>
    </body>
</html>
