<?php
$bdd = new PDO('mysql:host=localhost;dbname=locationlogement;charset=utf8', 'root', '');
$reponse = $bdd->query('SELECT * FROM users');
while ($donnees = $reponse->fetch()){
$nom = $donnees['user_nom'];
$prenom = $donnees['user_prenom'];
$mail = $donnees['user_mail'];
$mdp = $donnees['user_mdp'];
$avatar = $donnees['user_avatar'];
}

?>
<div class="container col-6">
    <form class="form-signin" method="post">
        <h2 class="form-signin-heading">Connexion à l'administration</h2>
        <label for="inputEmail" class="sr-only">Adresse email</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Adresse email" required="" autofocus="" style="margin:10px 0;">
        <label for="inputPassword" class="sr-only">Mot de passe</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Mot de passe" required="" style="margin:10px 0;">

        <button class="btn btn-lg btn-primary btn-block" type="submit">Se connecter</button>
    </form>
</div>