<div class="container col-6 py-5">
    <form class="form-signin" method="post" action="validlogin">
        <h2 class="form-signin-heading text-center">Connexion à l'administration de Location logement</h2>
        <label for="inputEmail" class="sr-only">Adresse email</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Adresse email" required="" autofocus="" style="margin:10px 0;" name="email">
        <label for="inputPassword" class="sr-only">Mot de passe</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Mot de passe" required="" style="margin:10px 0;" name="password">
        <button class="btn btn-lg btn-primary btn-block" type="submit">Se connecter</button>
    </form>
</div>