<div class="container">
  <form action="validform" method="post">
    <div class="form-group row">
      <label for="inputTitre" class="col-sm-2 col-form-label">Titre</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="inputTitre" placeholder="Titre du logement" name="titre">
      </div>
    </div>

    <div class="form-group row">
      <label for="inputRegion" class="col-sm-2 col-form-label">Région</label>
      <div class="col-sm-10">
      <select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="inputRegion" name="region">
            <option selected disabled>Séléctionner une région</option>
            <option>Auvergne-Rhône-Alpes</option><option>Bourgogne-Franche-Comté</option>
            <option>Bretagne</option><option>Centre-Val de Loire</option>
            <option>Corse</option><option>Grand Est</option>
            <option>Hauts-de-France</option><option>Île-de-France</option>
            <option>Normandie</option><option>Nouvelle-Aquitaine</option>
            <option>Occitanie</option><option>Pays de la Loire</option>
            <option>Provence-Alpes-Côte d'Azur</option><option>Guadeloupe</option>
            <option>Guyane</option><option>Martinique</option>
            <option>La Réunion</option><option>Mayotte</option>
        </select>
        </div>
    </div>

    <div class="form-group row">
          <label for="inputType" class="col-sm-2 col-form-label">Type de bien</label>
          <div class="col-sm-10">
          <select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="inputType" name="type">
                <option selected disabled>Séléctionner un type</option>
                <option>Appartement</option>
                <option>Maison</option>
            </select>
          </div>
    </div>

    <div class="form-group row">
          <label for="inputAdresse" class="col-sm-2 col-form-label">Adresse</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="inputAdresse" placeholder="Adresse du logement" name="adresse">
          </div>
    </div>

    <div class="form-group row">
          <label for="inputVille" class="col-sm-2 col-form-label">Ville</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="inputVille" placeholder="Ville du logement" name="ville">
          </div>
    </div>

    <div class="form-group row">
          <label for="inputCp" class="col-sm-2 col-form-label">Code postal</label>
          <div class="col-sm-10">
            <input type="number" min=0 class="form-control" id="inputCp" placeholder="Code postal du logement" name="cp">
          </div>
    </div>

    <div class="form-group row">
              <label for="inputSurface" class="col-sm-2 col-form-label">Surface (m²)</label>
              <div class="col-sm-10">
                <input type="number" min=0 class="form-control" id="inputSurface" placeholder="Surface du logement" name="surface">
              </div>
    </div>

    <div class="form-group row">
              <label for="inputPiece" class="col-sm-2 col-form-label">Nombre de pièces</label>
              <div class="col-sm-10">
                <input type="number" min="0" class="form-control" id="inputPiece" placeholder="Nombre de pièce du logement" name="nbpiece">
              </div>
    </div>

    <div class="form-group row">
          <label for="inputMeuble" class="col-sm-2 col-form-label">Meublé</label>
          <div class="col-sm-10">
          <select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="inputMeuble" name="meuble">
                <option selected disabled>Séléctionner oui / non</option>
                <option>Oui</option>
                <option>Non</option>
            </select>
          </div>
    </div>

    <div class="form-group row">
                  <label for="inputPrix" class="col-sm-2 col-form-label">Prix (€)</label>
                  <div class="col-sm-10">
                    <input type="number" min="0" class="form-control" id="inputPrix" placeholder="Prix du logement" name="prix">
                  </div>
    </div>

    <div class="form-group row">
        <label for="inputDescription" class="col-sm-2 col-form-label">Description</label>
        <div class="col-sm-10">
            <textarea class="form-control" id="inputDescription" rows="5" placeholder="Description du logement" name="description"></textarea>
        </div>
    </div>

    <div class="form-group row">
                  <label for="inputImage" class="col-sm-2 col-form-label">Image (url)</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="inputImage" placeholder="Image du logement" name="image">
                  </div>
    </div>

    <div class="form-group row">
      <div class="offset-sm-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Enregistrer</button>
      </div>
    </div>
  </form>
</div>