<div class="tools col-12 mb-5">
    <div class="container">
        <div class="row">
            <div class="col-6"><a href="/application/list"><i class="fa fa-long-arrow-left" aria-hidden="true"></i> Retour aux résultats</a> </div>
        </div>
    </div>
</div>
<div class="fiche col-12">
    <div class="container">
       <div class="row">
           <div class="col-12 col-md-8 mb-4">
               <div class="row">
                   <div class="col-12" style="height: 250px;background : url('http://www.eiffage-immobilier.fr/files/live/sites/eiffage-immo/files/contributed/visuels-programmes/appartement-neuf-nice-stella-rocca-diapo4.jpg') center no-repeat;background-size:cover;"></div>
                   <div class="col-12 p-3 general-desc mb-3">
                       <div class="row">
                           <small class="col-12 type">Appartement</small>
                           <h2 class="col-12 libelle">Nom du bien</h2>
                           <div class="col-12 no-padding txt-left">
                               <label class="flex"><i class="fa fa-map-marker" aria-hidden="true"></i> Paris 20 (75020)</label>
                           </div>
                           <div class="col-12 no-padding txt-left">
                               <label> <i class="fa fa-arrows-alt" aria-hidden="true"></i> 30m²</label>
                           </div>
                           <div class="col-12 no-padding txt-left">
                               <label> <i class="fa fa-eur" aria-hidden="true"></i> 890 C.C</label>
                           </div>
                           <div class="col-12 no-padding txt-left">
                               <label> <i class="fa fa-bed" aria-hidden="true"></i>1 pièce</label>
                           </div>
                       </div>
                   </div>
                   <div class="col-12">
                        <div class="row">
                            <div class="col-12 libelle">Description :</div>
                            <p class="col-12">
                                desc
                            </p>
                        </div>
                   </div>
                   <div class="col-12">
                       <div class="row">
                           <div class="col-12 libelle">Options :</div>
                           <div class="col-3">Digicode</div>
                           <div class="col-3">Interphone</div>
                           <div class="col-3">Ascenseur</div>
                       </div>
                   </div>
                   <div class="col-12">
                       <div class="row">
                           <div class="col-12 libelle">Partager cette annonce :</div>
                           <div class="col-12">
                               <div class="col-2 float-left">
                                    <a href="" class="social-link f-link"><i class="fa fa-circle fa-stack-2x "></i><i class="fa fa-facebook fa-stack-1x fa-inverse" aria-hidden="true"></i></a>
                               </div>
                               <div class="col-2 float-left">
                                   <a href="" class="social-link t-link"><i class="fa fa-circle fa-stack-2x"></i><i class="fa fa-twitter fa-stack-1x fa-inverse" aria-hidden="true"></i></a>
                               </div>
                               <div class="col-2 float-left text-center">
                                   <a href="" class="social-link g-link"><i class="fa fa-2x fa-google-plus-circle" aria-hidden="true"></i></a>
                               </div>
                           </div>
                       </div>
                   </div>
               </div>
           </div>
           <div class="col-md-4 col-12">
               <div class="row m-0">
                   <div class="col-12 contact p-3">
                       <div class="row">
                           <div class="col-12 text-center p-0 title mb-4">Contactez le propriétaire</div>
                           <form class="col-12">
                               <div class="row">
                                   <div class="col-12 mb-2">
                                       <input type="text" class="col-12 contact-text contact-name" placeholder="Nom">
                                       <i class="fa fa-user" aria-hidden="true"></i>
                                   </div>
                                   <div class="col-12 mb-2">
                                       <input type="email" class="col-12 contact-text contact-mail" placeholder="Email">
                                       <i class="fa fa-envelope" aria-hidden="true"></i>
                                   </div>
                                   <div class="col-12 mb-2">
                                       <input type="text" class="col-12 contact-text contact-phone" placeholder="Phone">
                                       <i class="fa fa-phone" aria-hidden="true"></i>
                                   </div>
                                   <div class="col-12 mb-2">
                                       <input type="submit" class="col-12 contact-submit" value="Envoyer">
                                   </div>
                                   <small class="col-12">
                                       Vos informations sont traitées et restent confidentielles conformément à la loi « informatique et libertés »
                                   </small>
                               </div>
                           </form>
                       </div>
                   </div>
               </div>
           </div>
       </div>
    </div>
</div>