<div class="col-12 recherche p-0">
    <div class="container pb-5">
        <div class="col-12">
            <div class="row">
                <h2 class="col-12 text-uppercase">Recherche Rapide</h2>
                <div class="col-md-3 col-lg-2">
                    <div class="row m-0">
                        <div class="text-uppercase search-cat-title col-12 pl-0">1. Type</div>
                        <div class="col-12 type-choice">
                            <div class="col-12 box">
                                <input type="checkbox" name="appartement" id="appartement">
                                <label for="appartement" class="col-12 m-0 text-center">
                                    <span style="font-size :40px !important;" class="icon-appartement col-xs-12 padding-top-10"></span>
                                    <span class="col-12 search-box-span">Appartement</span>
                                </label>
                            </div>
                            <hr>
                            <div class="col-12 box">
                                <input type="checkbox" name="maison" id="maison">
                                <label for="maison" class="col-12 m-0 text-center">
                                    <span style="font-size :35px !important;" class="icon-maison col-xs-12 padding-top-10"></span>
                                    <span class="col-12 search-box-span">Maison</span>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-lg-4 col-xl-4">
                    <div class="row m-0">
                        <div class="text-uppercase search-cat-title col-12 pl-0">2. Loyer & Surface</div>
                        <div class="loyer-choice col-12">
                            <div class="row">
                                <small class="col-6 pl-0 text-right text-uppercase search-cat-title">Loyer entre</small>
                                <div class="col-6 p-0 mb-3"><input class="col-12" type="number" step="10" name="loyer-min" min="0" placeholder="Loyer min."></div>
                                <small class="col-6 pl-0 text-right text-uppercase search-cat-title">et</small>
                                <div class="col-6 p-0 mb-3"><input class="col-12" type="number" step="10" name="loyer-max" min="0" placeholder="Loyer max."></div>
                            </div>
                        </div>
                        <div class="loyer-choice col-12">
                            <div class="row">
                                <small class="col-6 pl-0 text-right text-uppercase search-cat-title">Surface entre</small>
                                <div class="col-6 p-0 mb-3"><input class="col-12" type="number" step="5" name="surface-min" min="0" placeholder="Surface min."></div>
                                <small class="col-6 pl-0 text-right text-uppercase search-cat-title">et</small>
                                <div class="col-6 p-0"><input class="col-12" type="number" step="5" name="surface-max" min="0" placeholder="Surface max."></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-5 col-lg-4 col-xl-4">
                    <div class="row m-0">
                        <div class="text-uppercase search-cat-title col-12 pl-0">3. Nb pièces & meublage</div>
                        <div class="loyer-choice col-12">
                            <div class="row">
                                <small class="col-6 pl-0 text-right text-uppercase search-cat-title">Pièces entre</small>
                                <div class="col-6 p-0 mb-3"><input class="col-12" type="number" name="pieces-min" min="0" placeholder="Pièces min."></div>
                                <small class="col-6 pl-0 text-right text-uppercase search-cat-title">et</small>
                                <div class="col-6 p-0"><input class="col-12" type="number" name="pieces-max" min="0" placeholder="Pièces max."></div>
                            </div>
                        </div>
                        <div class="loyer-choice col-12">
                            <div class="row">
                                <small class="col-6 pl-0 text-right text-uppercase search-cat-title">Meublé</small>
                                <div class="col-6 p-0 mb-3"><input class="" type="checkbox" name="meuble"></div>
                                <small class="col-6 pl-0 text-right text-uppercase search-cat-title">Non meublé</small>
                                <div class="col-6 p-0"><input class="" type="checkbox" name="non-meuble"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-lg-2 py-3">
                    <input type="submit" class="col-12" value="Rechercher">
                </div>
                <div class="col-12" id="accordion" role="tablist" aria-multiselectable="false">
                    <div class="card">
                        <div class="card-header" role="tab" id="headingOne">
                            <h5 class="mb-0">
                                <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                                    <i class="fa fa-plus" aria-hidden="true"></i> Plus de critères
                                </a>
                            </h5>
                        </div>
                        <div id="collapseOne" class="collapse" role="tabpanel" aria-labelledby="headingOne">
                            <div class="card-block">
                                aaa
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="results col-12 p-0 mt-5">
    <div class="container">
        <div class="col-12">
            <div class="row">
                <a href="/application/fiche" class="col-12 p-0 result-link">
                    <div id="programme-liste-1" class="col-12 flex result-box row mb-4 pl-0" style="height: 277px;">
                        <div class="col-12 col-sm-4 float-left search-img" style="background : url('http://www.eiffage-immobilier.fr/files/live/sites/eiffage-immo/files/contributed/visuels-programmes/appartement-neuf-nice-stella-rocca-diapo4.jpg') center no-repeat;background-size:cover;"></div>
                        <span style="color: #3F51B5;font-size :40px !important;position: absolute;right:15px;top:15px;" class="icon-appartement padding-top-10"></span>
                        <div class="col-12 col-sm-8 float-left details p-3">
                            <div class="row m-0">
                                <div class="p-0 col-12">
                                    <small class="col-12 no-padding txt-left p-0">Appartement</small>
                                    <p class="libelle col-12 no-padding p-0">Nom du bien</p>
                                </div>
                            </div>
                            <hr>
                            <div class="row flex">
                                <div class="col-lg-8 col-12 row ">
                                    <div class="col-6 no-padding txt-left">
                                        <label class="flex"><i class="fa fa-map-marker" aria-hidden="true"></i> Paris 20 (75020)</label>
                                    </div>
                                    <div class="col-6 no-padding txt-left">
                                        <label> <i class="fa fa-arrows-alt" aria-hidden="true"></i> 30m²</label>
                                    </div>
                                    <div class="col-6 no-padding txt-left">
                                        <label> <i class="fa fa-eur" aria-hidden="true"></i> 890 C.C</label>
                                    </div>
                                    <div class="col-6 no-padding txt-left">
                                        <label> <i class="fa fa-bed" aria-hidden="true"></i>1 pièce</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>