<?php

$id = $_GET['id'];

$bdd = new PDO('mysql:host=localhost;dbname=locationlogement;charset=utf8', 'root', '');
$reponse = $bdd->query("SELECT * FROM logement WHERE logement_id=".$id.";");
while ($donnees = $reponse->fetch()){

?>

<div class="container">
  <form action="modifform?id=<?= $id;?>" method="post">
    <div class="form-group row">
      <label for="inputTitre" class="col-sm-2 col-form-label">Titre</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="inputTitre" value="<?php echo $donnees['logement_titre']; ?>" name="titre">
      </div>
    </div>

    <div class="form-group row">
      <label for="inputRegion" class="col-sm-2 col-form-label">Région</label>
      <div class="col-sm-10">
      <select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="inputRegion" name="region">
            <option selected ><?php echo $donnees['logement_region']?></option>
            <option>Auvergne-Rhône-Alpes</option><option>Bourgogne-Franche-Comté</option>
            <option>Bretagne</option><option>Centre-Val de Loire</option>
            <option>Corse</option><option>Grand Est</option>
            <option>Hauts-de-France</option><option>Île-de-France</option>
            <option>Normandie</option><option>Nouvelle-Aquitaine</option>
            <option>Occitanie</option><option>Pays de la Loire</option>
            <option>Provence-Alpes-Côte d'Azur</option><option>Guadeloupe</option>
            <option>Guyane</option><option>Martinique</option>
            <option>La Réunion</option><option>Mayotte</option>
        </select>
        </div>
    </div>

    <div class="form-group row">
          <label for="inputType" class="col-sm-2 col-form-label">Type de bien</label>
          <div class="col-sm-10">
          <select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="inputType" name="type">
                <option selected ><?php echo $donnees['logementnt_type']; ?></option>
                <option>Appartement</option>
                <option>Maison</option>
            </select>
          </div>
    </div>

    <div class="form-group row">
          <label for="inputAdresse" class="col-sm-2 col-form-label">Adresse</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="inputAdresse" value="<?php echo $donnees['logement_adresse']; ?>" name="adresse">
          </div>
    </div>

    <div class="form-group row">
          <label for="inputVille" class="col-sm-2 col-form-label">Ville</label>
          <div class="col-sm-10">
            <input type="text" class="form-control" id="inputVille" value="<?php echo $donnees['logement_ville']; ?>" name="ville">
          </div>
    </div>

    <div class="form-group row">
          <label for="inputCp" class="col-sm-2 col-form-label">Code postal</label>
          <div class="col-sm-10">
            <input type="number" min=0 class="form-control" id="inputCp" value="<?php echo $donnees['logement_cp']; ?>" name="cp">
          </div>
    </div>

    <div class="form-group row">
              <label for="inputSurface" class="col-sm-2 col-form-label">Surface (m²)</label>
              <div class="col-sm-10">
                <input type="number" min=0 class="form-control" id="inputSurface" value="<?php echo $donnees['logement_surface']; ?>" name="surface">
              </div>
    </div>

    <div class="form-group row">
              <label for="inputPiece" class="col-sm-2 col-form-label">Nombre de pièces</label>
              <div class="col-sm-10">
                <input type="number" min="0" class="form-control" id="inputPiece" value="<?php echo $donnees['logement_nb_piece']; ?>" name="nbpiece">
              </div>
    </div>

    <div class="form-group row">
          <label for="inputMeuble" class="col-sm-2 col-form-label">Meublé</label>
          <div class="col-sm-10">
          <select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="inputMeuble" name="meuble">
                <option selected><?php echo $donnees['logement_meuble']; ?></option>
                <option>Oui</option>
                <option>Non</option>
            </select>
          </div>
    </div>

    <div class="form-group row">
                  <label for="inputPrix" class="col-sm-2 col-form-label">Prix (€)</label>
                  <div class="col-sm-10">
                    <input type="number" min="0" class="form-control" id="inputPrix" value="<?php echo $donnees['logement_prix']; ?>" name="prix">
                  </div>
    </div>

    <div class="form-group row">
        <label for="inputDescription" class="col-sm-2 col-form-label">Description</label>
        <div class="col-sm-10">
            <textarea class="form-control" id="inputDescription" rows="5" name="description"><?php echo $donnees['logement_description']; ?></textarea>
        </div>
    </div>

    <div class="form-group row">
                  <label for="inputImage" class="col-sm-2 col-form-label">Image (url)</label>
                  <div class="col-sm-10">
                    <input type="text" class="form-control" id="inputImage" value="<?php echo $donnees['logement_image']; ?>" name="image">
                  </div>
    </div>
<?php } ?>
    <div class="form-group row">
      <div class="offset-sm-2 col-sm-10">
        <button type="submit" class="btn btn-primary">Modifier</button>
      </div>
    </div>
  </form>
</div>