<?php

$servername = "localhost";
$username = "root";
$password = "";
$dbname = "locationlogement";

$conn = new PDO("mysql:host=$servername;dbname=$dbname", $username, $password);
$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$sql = "DELETE FROM logement WHERE logement_id=".$id.";";
$conn->exec($sql);

?>

Votre logement à bien été supprimé.

<a class="btn btn-success" href="listadmin" role="button">Retour à la liste des logements</a>